FROM nvidia/cuda:12.9.1-cudnn-runtime-ubuntu22.04

# `ffmpeg` is installed because without it `gradio` won't work with mp3(possible others as well) files
# hadolint ignore=DL3008,DL3015,DL4006

RUN apt update && apt install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa -y && \
    apt update && \
    apt install -y python3.12 python3.12-venv python3.12-dev && \
    ln -s /usr/bin/python3.12 /usr/bin/python3

#uv latest
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /usr/local/bin/

# Switch to the non-root user for all subsequent commands and entrypoint
USER 1000

# Optional but recommended: set the working directory to the new user's home
WORKDIR /home/vllm

# https://docs.astral.sh/uv/guides/integration/docker/#intermediate-layers
RUN --mount=type=cache,target=/home/vllm/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project

COPY ./src ./pyproject.toml ./uv.lock ./

RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --frozen --extra ui

ENV WHISPER__MODEL=Systran/faster-whisper-large-v3
ENV WHISPER__INFERENCE_DEVICE=auto
ENV UVICORN_HOST=0.0.0.0
ENV UVICORN_PORT=8000
CMD ["uv", "run", "uvicorn", "--factory", "faster_whisper_server.main:create_app"]
