FROM nvidia/cuda:12.9.1-cudnn-runtime-ubuntu22.04

RUN apt update && apt install -y software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa -y && \
    apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y python3.12 python3.12-venv python3.12-dev && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 1 && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.12 2 && \
    update-alternatives --set python3 /usr/bin/python3.12

# uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /usr/local/bin/

# -------------------------------
# Create real user "vllm"
# -------------------------------
RUN useradd -m -u 1000 vllm
USER vllm
ENV HOME=/home/vllm
WORKDIR /home/vllm

# First sync layer (before project files)
RUN --mount=type=cache,target=/home/vllm/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project

COPY ./src ./pyproject.toml ./uv.lock ./

RUN --mount=type=cache,target=/home/vllm/.cache/uv \
    uv sync --frozen --extra ui

ENV WHISPER__MODEL=Systran/faster-whisper-large-v3
ENV WHISPER__INFERENCE_DEVICE=auto
ENV UVICORN_HOST=0.0.0.0
ENV UVICORN_PORT=8000

CMD ["uv", "run", "uvicorn", "--factory", "faster_whisper_server.main:create_app"]
